const products = [
    {
        id:1,
        title:"Whoper",
        image:"https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-burger-king-argentina//home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Whopper.png",
        price:1200,
        stock:50,
        desc:"100% real no fake.",
        category:"",
        text:"Ahora nuestra Whopper es sin conservantes, colorantes ni saborizantes artificiales. Con todo el sabor a la parrilla, jugosos tomates, lechuga recién cortada, mayonesa, pepinos y cebollas en rodajas, sobre un suave pan con semillitas de ajonjolí. Pedila así: Whopper y nada más que Whopper, pero con papas y gaseosa ;)",
    },
    {
        id:2,
        title:"Whoper Doble",
        image:"https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina//home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/BK_WEB_WHOPER-DOBLE-_1200X800_020822.png",
        price:1900,
        stock:50,
        desc:"2 veces más perfecta",
        category:"",
        text:"Disfruta el doble con 2 carnes a la parrilla, pan, salsa ciboulette, ketchup, cebolla, tomate, pepinos y lechuga.",
    },
    {
        id:3,
        title:"Stacker triple",
        image:"https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-burger-king-argentina//home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Stacker-Triple.png",
        price:2200,
        stock:20,
        desc:"Manijeá fuerte",
        category:"",
        text:"3 carnes a la parrilla, salsa stacker, pan, queso cheddar, panceta. Muy potente.",
    },
    {
        id:4,
        title:"Hamburguesa con queso",
        image:"https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-burger-king-argentina//home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Hamburguesa-con-Queso.png",
        price:900,
        stock:80,
        desc:"Todo es mejor con queso",
        category:"",
        text:"Carne a la parrilla, pan, queso cheddar, mostaza y ketchup. Apta para sumarle más queso ;)",
    },
    {
        id:5,
        title:"Stacker quintuple",
        image:"https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-burger-king-argentina//home/ubuntu/wordpress/web/app/uploads/sites/5/2021/04/stacker-quintuple.png",
        price:2950,
        stock:15,
        desc:"Hecha por manijas, para manijas.",
        category:"",
        text:"5 carnes a la parri, salsa stacker, pan, queso cheddar, panceta. Solo para expertos",
    },
    {
        id:6,
        title:"Doble JyQ XL",
        image:"https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-burger-king-argentina//home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Doble-Jamon-y-Queso-XL.png",
        price:1600,
        stock:40,
        desc:"Combinación perfecta.",
        category:"",
        text:"Disfruta de esta maravilla hecha con 2 carnes a la parrilla + jamón y queso.",
    }
];
export default products;